### ISSUE TITLE
quote as proc macro

### ISSUE THREAD

**Issue by Robbepop** [dtolnay/quote#113]
In regards of https://github.com/dtolnay/quote/pull/97 and me remembering that proc macro support for the original quote crate was planned.
What would it take to do so and what are the foreseeable difficulties implementing this efficiently?
I think this could be important for the eco system since so many crates (proc-macro crates) are depending on quote.
Lifting the remaining limitations and implementing quote as proc macro efficiently would be beneficial for so many crates out there.

**Comment by Goncalerta** [comment]
If you have any ideas to make [`proc-quote`](https://crates.io/crates/proc-quote) more efficient, I would gladly accept pull requests. 

I don't think @dtolnay intends on changing the implementation of the original quote crate to a proc-macro, at least for now, based on what he said in [request-for-implementation#8](https://github.com/dtolnay/request-for-implementation/issues/8):
> Originally filed as dtolnay/quote#82 but I would like this to begin its life as a separate library.

Regarding the limitations on the original quote, some progress appears to be being made in #109.

**Comment by dtolnay** [comment]
The only remaining reason to do a proc macro would be if it is able to emit code that compiles more efficiently than what is emitted by the macro_rules quote *and* the difference is significant enough to make up for time compiling the proc macro in typical usage. What I would look for is serde_derive end to end compile time including all dependencies being <90% of current serde_derive compile time based on macro_rules quote. I put up some old prototypes focused on compile time in #115 #116 #117 but the best one is only single digit percent faster end to end on serde_derive.

I'll close this issue since for now the plan is to resolve all the limitations without using a proc macro.
