### ISSUE TITLE
Consider supporting repetition where element type is Result

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/quote#143]
Something like this:

```rust
use proc_macro2::TokenStream;
use quote::quote;
use syn::Result;

fn item(i: usize) -> Result<TokenStream> {
    Ok(quote!(#i))
}

fn all_items() -> Result<TokenStream> {
    let iter = (0..4).map(item);

    Ok(quote! {
        #(#iter),*
    })
}

fn main() {
    println!("{}", all_items().unwrap());
}
```

The semantics should be the same as if the loop we generate were operating on `elem?` instead of `elem` for each Result in the iterator.

The current workaround is to collect to Result\<Vec\<_\>\> first.

```rust
let v = (0..4).map(item).collect::<Result<Vec<_>>>()?;
```

**Comment by mystor** [comment]
We might want to have it be clear that we're expecting a result in that scenario, but I'm not sure how to do that backwards-compatibly. I might suggest `quote!(#(#iter?),*)`, but that unfortunately already has a meaning. I'm not sure I love having `quote!` implicitly insert returns into your function if the type of an iterator's item happens to be a `Result`, but maybe it's OK?

**Comment by dtolnay** [comment]
Let's not do this after all. Using `collect::<Result<Vec<_>>>()?` beforehand is fine and preferable over quote inserting invisible early returns.

**Comment by shahn** [comment]
I stumbled across this issue because I had exactly this usecase. Would you maybe be willing to revisit this? There's a certain overhead to collecting into a result beforehand and it can't really be avoided without support from `quote!`. Right now, iterators over `Result`s just do not compile, so all existing code would continue to work seamlessly and no new syntax would be required
