### ISSUE TITLE
Option<T> repetitions do not work

### ISSUE THREAD

**Issue by lroux-at-jellysmack** [dtolnay/quote#213]
Hello,

While trying to do the following thing,
```rust
fn test(option: Option<TokenStream>) -> TokenStream {
    quote! {
        #(#option)*
    }
}
```
it gives me the following error:
```sh
expected struct `HasIterator`, found struct `ThereIsNoIteratorInRepetition`
```

The type `Option<T>` does not work in repetitions (`#()*`), while stated otherwise in the README.md [here](https://github.com/dtolnay/quote/blame/master/README.md#L87), since `Option<T>` implements `IntoIterator`.

I also found something stating the inverse [here](https://docs.rs/quote/latest/quote/macro.quote.html):
> The variables in an interpolation may be a Vec, slice, BTreeSet, or any Iterator.

I ended up fixing my code by doing this:
```diff
 fn test(option: Option<TokenStream>) -> TokenStream {
+    let option = option.iter();
     quote! {
         #(#option)*
     }
 }
```

---

Also I have a few questions:
- What could I do to recreate the optional behavior of declarative macros using `$()?`, since `#()*` does not work out of the box ?
- Could this `IntoIterator` mechanism be introduced in order to achieve this without requiring `.iter()` everywhere ?

Thanks :)

**Comment by ahl** [comment]
This may not address your actual use, but you can just do

```rust
fn test(option: Option<TokenStream>) -> TokenStream {
    quote! {
        #option
    }
}
```

This precludes other fancy stuff you might want to do inside the `#( ... )*` repetition specifier.

Agreed that the docs appear to be inaccurate based on the current implementation: https://github.com/dtolnay/quote/blob/ae25ab6a5bde0efc79d85a8211b76d0bdd08dca7/src/runtime.rs#L54

**Comment by coolreader18** [comment]
This might count as a breaking change, but what if there was a `#( #var )?` optionality specifier? Basically the same as `#()*` but expecting the variable to be an option

**Comment by cyqsimon** [comment]
Ran into this problem today; ended up doing this. Not particularly pretty but it works.

```rust
let vec_of_options: Vec<Option<String>> = vec![/* stuff */];
let vec_of_options_tokenised: Vec<TokenStream> = vec_of_options
    .into_iter()
    .map(|opt| match opt {
        Some(text) => quote! { Some(#text) },
        None => quote! { None },
    })
    .collect();
// in quote macro, use `vec_of_options_tokenised` instead of `vec_of_options`
```

**Comment by dtolnay** [comment]
- `quote! { ... #option ... }`

or

- `let option = option.iter(); quote! { ... #(... #option ...)* ... }`

or

- `let option = option.map(|thing| quote! { ... #thing ... }); quote! { ... #option ... }`

are the recommended solutions.

I put up #280 to fix the documentation about "anything that implements IntoIterator".

**Comment by Qix-** [comment]
The problem with this @dtolnay is that `iter()` can only be used once and other usages of `Option<T>` are completely unergonomic.

---

> `quote! { ... #option ... }`

```rust
let maybe_elem_ident = if include_elem { Some(quote! { the_elem }) } else { None };

quote! {
    let foo = (#maybe_elem_ident, bar);
}
```

If `None`, that evaluates to `let foo = (, bar)` with is a [syntax error](https://godbolt.org/z/Ks6MaGd64).

> `let option = option.iter(); quote! { ... #(... #option ...)* ... }`

```rust
let maybe_elem_ident_original = if include_elem { Some(quote! { the_elem }) } else { None };
let maybe_elem_ident = maybe_elem_ident_original.iter();

quote! {
    let foo = (#(#maybe_elem_ident,)* bar,); // either (the_elem, bar,) or just (bar,) - both are tuples
    let baz = (#(#maybe_elem_ident,)* qux,); // either (the_elem, qux,) or just (qux,) - both are tuples
}
```

Now you get a syntax error; `maybe_elem_ident` was already moved from the `let foo` line.

You can o course construct multiple `quote!()`s while re-assigning all of the `let maybe_elem_ident = maybe_elem_ident_original.iter();` over and over again, then do a final `quote!{}` that includes all of them, but that's adding more cruft to proc-macros which are already _very_ crufty.

> `let option = option.map(|thing| quote! { ... #thing ... }); quote! { ... #option ... }`

Taking the example from above, this isn't _much_ better, because now you have to assign a new variable for literally every combination of optional syntaxes you have.

---

... which leads to the obvious solution here that maps nicely to `macro_rules!` syntax and is what @coolreader18 suggested (which I was actually pretty surprised `quote` didn't do out of the box):

```rust
let maybe_elem_ident = if include_elem { Some(quote! { the_elem }) } else { None };

quote! {
    let foo = (#(#maybe_elem_ident,)? bar,);
}
```

_Please_ reconsider.
