### ISSUE TITLE
Question / Feature Request: Support generation of raw string literals

### ISSUE THREAD

**Issue by Carter12s** [dtolnay/quote#277]
It is unclear to me how I can use quote! to generate a raw string literal cleanly?

This panics as it isn't a valid ident
```rust
    let expanded = format_ident!("r#\"{}\"#r", definition);
```

From reading the documentation and experimenting I can't find an obvious solution? It would be nice to provide an off the shelf solution for this.

The workaround I came up with was:

```rust
pub fn generate_raw_string_literal(value: &str) -> TokenStream {
    let wrapped = format!("r#\"{}\"#", value);
    TokenStream::from_str(&wrapped).unwrap()
}
```

Which doesn't seem like the best way of doing it... It would be nice to provide a built in solution, or at least add an equivalent of this workaround to the documentation.

**Comment by dtolnay** [comment]
The solution you arrived at is fine, although I would recommend `Literal::from_str` instead of `TokenStream::from_str` if the intent is to represent a single literal token. Also you would need to make sure the string contents do not contain `"#`.

If you'd like to see a more specific API dedicated to this use case, the right way to follow up would be an API Change Proposal (https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html) for `proc_macro::Literal`. However, it seems pretty unlikely to me that a raw string Literal constructor would be accepted because the distinction between raw and cooked strings is not normally a distinction that proc macros would need to care about in macro output.

**Comment by nyurik** [comment]
For anyone else finding this issue - this seem to work ok. This is a slightly modified Insta code from https://github.com/mitsuhiko/insta/pull/748/files

```rust
    let hashes = value
        .split('"')
        .skip(1) // Skip the first part which is before the first quote
        .map(|s| s.chars().take_while(|&c| c == '#').count() + 1)
        .max()
        .unwrap_or_default();
    let hashes = "#".repeat(hashes);
    let literal = Literal::from_str(&format!("r{hashes}\"{value}\"{hashes}")).unwrap();
    quote! { #literal }
```

**Comment by nyurik** [comment]
@dtolnay come to think of it - would you mind if I create a dedicated method for this as part of your quote crate?  This clearly is needed by more than just one person, yet adding these few lines into a new crate seems overkill. Would you mind if I submit a PR for it?

**Comment by dtolnay** [comment]
Please do an ACP for proc_macro.
