### ISSUE TITLE
Make it easy to compare "Tokens"

### ISSUE THREAD

**Issue by federicomenaquintero** [dtolnay/quote#50]
I'd like to have some tests for "am I generating the correct stuff?".

Let's say I have a bit of my AST and I impl ToTokens for it.  I'd like to be able to test that the generated tokens match some known-good ones.

Maybe it would be enough to have PartialEq implemented for Tokens?  They would match if the tokens are the same, ignoring the spans?

**Comment by mystor** [comment]
`PartialEq` wouldn't work well here, because we don't want to consider two tokens equal if they don't have the same spans in the general case.

I do want to have some sort of `spanless_eq()` or similar method which does the right thing & compares the TokenStreams ignoring any spans. I haven't gotten around to implementing that though.

**Comment by mystor** [comment]
We ended up adding `PartialEq` for Tokens in #59

**Comment by federicomenaquintero** [comment]
Thanks, this is good news!
