### ISSUE TITLE
Where is Ident?

### ISSUE THREAD

**Issue by gnzlbg** [dtolnay/quote#52]
The docs says that there is an `Ident` struct that allows interpolating a string without quotes: 
https://docs.rs/quote/0.3.15/quote/struct.Ident.html

But I cannot use it nor find where it should be within the library.

**Comment by gnzlbg** [comment]
It would also actually be great if the readme example could show how to interpolate a simple string using `quote!`.

**Comment by gnzlbg** [comment]
Never mind, it seems that it was removed it in favor of the proc macro2 crate. 

I just wasted one hour of my life, and looks that I am going to have to waste another one trying to learn how to use that instead by reading the source.

**Comment by dtolnay** [comment]
I would recommend only using the master branches if you have plenty of hours of your life to waste. Otherwise stick to the released versions or use a different library. The master branch is not sufficiently documented yet, is harder to use, and is still undergoing significant changes as part of Macros 2.0 work.

**Comment by gnzlbg** [comment]
@dtolnay sadly I work on one rust-lang-nursery crate (`stdsimd`) that uses the master branches of `syn`, `quote` and so on. If it were up to me it wouldn't do this, but it isn't up to me.
